homework3_test: homework3_main.o homework3_imp.o
	gcc -o -Wall -Wextra -Werror -o homework3_test homework3_main.o homework3_imp.o

homework3_main.o: homework3_main.c homework3.h
	gcc -Wall -Wextra -Werror -c homework3_main.c

homework3_imp.o: homework3_imp.c homework3.h
	gcc -Wall -Wextra -Werror -c homework3_imp.c
 